import { CheckCircle2, Home, Send } from 'lucide-react'
import { useEffect, useState } from 'react'
import { FieldError } from '../components/common/States'
import { useTenant } from '../context/TenantContext'
import { submitPublicForm } from '../services/inquiryService'
import { setAgencySeo } from '../utils/seo'

const initial = { full_name: '', phone: '', email: '', address: '', property_type: '', purpose: 'sale', expected_price: '', message: '' }

export default function ListPropertyPage() {
  const { agency } = useTenant(); const [form, setForm] = useState(initial); const [state, setState] = useState({ status: 'idle', error: '' })
  useEffect(() => setAgencySeo(agency, { title: `List your property | ${agency.name}`, description: `Tell ${agency.name} about a property you want to sell, rent, or value.` }), [agency])
  async function submit(event) { event.preventDefault(); setState({ status: 'submitting', error: '' }); try { await submitPublicForm(agency, { kind: 'valuation', full_name: form.full_name, phone: form.phone, email: form.email, message: form.message, metadata: { address: form.address, property_type: form.property_type, purpose: form.purpose, expected_price: form.expected_price } }); setForm(initial); setState({ status: 'success', error: '' }) } catch (error) { setState({ status: 'error', error: error.message }) } }
  if (state.status === 'success') return <main className="submission-success"><CheckCircle2 /><p className="eyebrow">Property details received</p><h1>Thank you for choosing {agency.name}.</h1><p>The agency has received your property request and will contact you to discuss the next step. Submitting this form does not publish the property automatically.</p><button className="button button-primary" onClick={() => setState({ status: 'idle', error: '' })}>Submit another property</button></main>
  return <main><section className="listing-intro"><div className="container listing-intro-grid"><div><p className="eyebrow">Sell, rent, or understand its value</p><h1>Tell us about your property.</h1><p>Share the essentials with {agency.name}. The team will review your request, contact you, and explain the listing or valuation process.</p><ul><li><CheckCircle2 />A direct response from the agency</li><li><CheckCircle2 />No property is published without review</li><li><CheckCircle2 />Clear next steps based on your goal</li></ul></div><div className="listing-icon"><Home /></div></div></section><section className="section"><form className="container property-submission-form" onSubmit={submit}><div className="form-intro"><p className="eyebrow">Property request</p><h2>Start with the essentials</h2><p>Fields marked with an asterisk are required.</p></div><div className="form-grid"><label>Full name *<input required value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} autoComplete="name" /></label><label>Phone number *<input required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} autoComplete="tel" /></label></div><label>Email address <span>(optional)</span><input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} autoComplete="email" /></label><label>Property address or location *<input required value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} placeholder="Tole, municipality, district" /></label><div className="form-grid"><label>Property type<select value={form.property_type} onChange={(e) => setForm({ ...form, property_type: e.target.value })}><option value="">Choose a type</option><option value="house">House</option><option value="land">Land</option><option value="apartment">Apartment</option><option value="flat">Flat</option><option value="commercial">Commercial</option><option value="office_space">Office space</option></select></label><label>Your goal<select value={form.purpose} onChange={(e) => setForm({ ...form, purpose: e.target.value })}><option value="sale">Sell</option><option value="rent">Rent out</option><option value="lease">Lease</option></select></label></div><label>Expected price <span>(optional)</span><input type="number" min="0" value={form.expected_price} onChange={(e) => setForm({ ...form, expected_price: e.target.value })} placeholder="NPR" /></label><label>Anything else we should know? <span>(optional)</span><textarea rows="5" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Property size, road access, preferred contact time, or other useful details." /></label><FieldError error={state.error} /><button className="button button-primary" disabled={state.status === 'submitting'}><Send />{state.status === 'submitting' ? 'Submitting…' : 'Send property details'}</button></form></section></main>
}
